### ISSUE TITLE
Improvement - Versioning contained within the code

### ISSUE THREAD

**Issue by dalgibbard** [danielebailo/couchdb-dump#11]
It would probably be a reasonable idea to set 'version=x.x' within the code, and offer this within the arguments that can be passed; ie:

```
./couchdb-dump.sh -V
CouchDB Dump - Version x.x
```

This will assist with identifying which version of the code someone is running if/when they report an issue.

**Comment by danielebailo** [comment]
solved with the last commit
https://github.com/danielebailo/couchdb-dump/commit/cdc6353f88bb07082f88741bd809b96fa4eedb0e
