### ISSUE TITLE
Improvement - Check Available Disk Space

### ISSUE THREAD

**Issue by dalgibbard** [danielebailo/couchdb-dump#14]
We should ideally be checking for available disk space where possible.
Note:
* We can't check this for the main export, as it's impossible to determine the completed output file size
* Everytime we run sed etc, it will create a tempfile, roughly equal to that of the original file (minus whatever we're cutting out).
* When running a restore which contains design files, we're creating a clone of the DB file (minus _design docs) so that we're not amending the original export (in case something fails, user wants to import again etc). We then run sed on that... which means at that point we need to account for approx "<DB_FILE_SIZE>*3" available disk space.

**Comment by dalgibbard** [comment]
For the main sed (the one which cuts the docs out) we could probably estimate the size reduction based on the approx number of chars to remove per line, multiplied by the line count. Then we could subtract that from the main file's size to establish a required space amount.

**Comment by dalgibbard** [comment]
Have got this factored into the changes im working on today. Should have it ready to merge in a couple of hours.

**Comment by dalgibbard** [comment]
Done now :)

**Comment by danielebailo** [comment]
good!

Daniele

http://www.danielebailo.it/ <http://danielebailo.wordpress.com/>


2015-02-16 17:12 GMT+01:00 Darren Gibbard <notifications@github.com>:
