### ISSUE TITLE
Backup & Restore database with docs with binary attachments

### ISSUE THREAD

**Issue by Telephonic** [danielebailo/couchdb-dump#2]
Great work on these scripts! Thank you for writing these and sharing. It's great to be able to just grab a copy of a whole CouchDB database.

Did you design the scripts in mind to handle binary attachments? We seem to able to download a full database that includes binary attachments. The backup file and the original database size are similar. However, when I try to restore this database dump with binary files, I get the following error:

{"error":"bad_request","reason":"invalid UTF-8 JSON"}

Have you come across the above error before?

I have been able to restore pure JSON (non binary) databases without any trouble. 

Thank you!

Graham
CTO, Telephonic

**Comment by dalgibbard** [comment]
FYI; I looked at this issue whilst contributing some other fixes; the main issue is that requesting the docs output doesn't 'print' the binary content; example:

```
{"docs":[
{"_id":"4685ca2ba841112ed63ba386c0000f5b","_rev":"2-92342d54acd87a4b4800cf51f99add09","value":"this is 3\" long"},
{"_id":"4685ca2ba841112ed63ba386c0001e56","_rev":"2-e1432ed19858cdbc8b5c0c0bbf38f76a","value":"this is my binary document","_attachments":{"esxi.tgz":{"content_type":"application/x-compressed-tar","revpos":2,"digest":"md5-K1F3CiyZT2AjIaR3n7dFSQ==","length":1697995,"stub":true}}}
]}
```

In order for these to be managed too, I suspect you'd need to scan your entire output for references to attachement and then, programatically download the binary separately.
Then, during restore, you'd again need to monitor for import of the document, strip the attachment stanza, and post-successful-import, push the binary file to the document again. (If you try and import the document without stripping the attachement segment, it will fail with "missing_stub" as the referenced file doesn't exist)

It's a bit long winded, and unfortunately out of scope for the changes that i've been looking to implement.

**Comment by danielebailo** [comment]
fixed here https://github.com/danielebailo/couchdb-dump/pull/8
