### ISSUE TITLE
Doesn't work in OS X 10.10

### ISSUE THREAD

**Issue by nicktacular** [danielebailo/couchdb-dump#20]
Great app! Just has some issues with BSD-style commands:

```ShellSession
[zero]couchdb-dump(master)→ ./couchdb-backup.sh -H thehost.whatever.com -d delivery-index -f db.json -b
./couchdb-backup.sh: line 157: nproc: command not found
expr: syntax error
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.2M    0 12.2M    0     0  1000k      0 --:--:--  0:00:12 --:--:--  799k
... INFO: File contains Windows carridge returns- converting...
du: illegal option -- B
usage: du [-H | -L | -P] [-a | -s | -d depth] [-c] [-h | -k | -m | -g] [-x] [-I mask] [file ...]
... ERROR: checkdiskspace() was not passed the correct arguments.
[zero]couchdb-dump(master %)→ uname -a
Darwin zero.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
```

**Comment by tciuro** [comment]
+1

I just saw that too.

**Comment by rajington** [comment]
+1

if the error is because of `nproc`, you can use `sysctl -n hw.ncpu`

**Comment by dalgibbard** [comment]
Ah nice one; I don't have a Mac, so its pretty fiddly for me to establish
what alternative commands there are. I'll check if sysctl is portable to
Linux too.

The other error is surrounding one of the flags I'm passing to du to work
out available disk space; could I trouble you to have a peek and see if
there's a Mac equivalent?

If there's no easily portable options, I may need to have two commands,
split by identified system type (worst case scenario)- what's the simplest
way of identifying a Mac on command line?

**Comment by nicktacular** [comment]
Identify OS X using `uname -a | grep -i darwin`:
```ShellSession
[zero]~→ uname -a | grep -i darwin
Darwin zero.local 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
```

For `du` instead of using `-BK` use just `-k` and you don't need to `sed` out `K` since it's not in the output:
```ShellSession
[zero]~→ du -P -k tracks.json 
44	tracks.json
```

For the number of CPUs (as @rajington says) you can use `sysctl` like so:

```ShellSession
[zero]~→ sysctl -n hw.ncpu
4
```

In either case, you could create a few bash functions for this. I'd offer a PR but not any time at the moment to do so.

Thanks for your great tool! I use this on Linux a lot now.

**Comment by danielebailo** [comment]
Darren,
sorry for coming back to you so late.
It looks like NIck Lyin already solved the issue, isn't it?

bye
Daniele

Daniele

http://www.danielebailo.it/


2015-04-16 23:49 GMT+02:00 Darren Gibbard <notifications@github.com>:

> Ah nice one; I don't have a Mac, so its pretty fiddly for me to establish
> what alternative commands there are. I'll check if sysctl is portable to
> Linux too.
>
> The other error is surrounding one of the flags I'm passing to du to work
> out available disk space; could I trouble you to have a peek and see if
> there's a Mac equivalent?
>
> If there's no easily portable options, I may need to have two commands,
> split by identified system type (worst case scenario)- what's the simplest
> way of identifying a Mac on command line?
>

**Comment by dalgibbard** [comment]
Yeah sort of; I'll raise a merge for it in a while maybe - I'd forgotten about it tbh :)
