### ISSUE TITLE
nproc missing in some environments

### ISSUE THREAD

**Issue by thecalle** [danielebailo/couchdb-dump#34]
line 166: cores=`nproc`
in some cases nproc command not present in OS.
better introducing a test: if nproc is null then cores=1

**Comment by dalgibbard** [comment]
Valid point to some extent- but out of curiosity, which OS are we referring to here, and why is nproc not available?
We popped a fix for this for OSX a while back, sounds like a similar alternative may be required for whatever scenario this is too :)

**Comment by thecalle** [comment]
arm7 embedded for example or someone that removed it...

**Comment by dalgibbard** [comment]
Makes sense; always interesting to know! :)

**Comment by thecalle** [comment]
Can I suggest:
if ! type "$nproc" > /dev/null; then
  cores=1
else
cores=`nproc`
fi

**Comment by dalgibbard** [comment]
Implemented as suggested :) thanks.
