### ISSUE TITLE
Possible to backup all databases 

### ISSUE THREAD

**Issue by raymatos** [danielebailo/couchdb-dump#44]
Is it possible to backup all available databases?

**Comment by dalgibbard** [comment]
Yes and no; the script itself doesn't directly support multi-DB backups; but there's nothing stopping you from scripting this yourself; ie:

Example, where all databases have the same user and password (ie. global admin):
```
USER=admin
PASS=password
HOST=127.0.0.1
PORT=5984

# Get all DBs (excluding system ones):
ALL_DBS=$(curl http://$USER:$PASS@$HOST:$PORT/_all_dbs  2>/dev/null | python -m json.tool | awk -F'"' '{print$2}' | grep -v "^_\|^$")

# Backup each found DB
for db in $ALL_DBS; do
    bash couchdb-backup.sh -b -H $HOST -P $PORT -u $USER -p $PASS -d $db -f ${db}_`date -I`.json
done
```

Does that help at all?
