### ISSUE TITLE
Attachment contents is only added for CouchDB versions above 1.6.0

### ISSUE THREAD

**Issue by csgui** [danielebailo/couchdb-dump#46]
Hello!

`attachments=true` in view API endpoints only works for CouchDB versions **above** `1.6.0`.

[Here](https://issues.apache.org/jira/browse/COUCHDB-1923) you have more information about this feature.

Thanks!

**Comment by dalgibbard** [comment]
Need to:
* Identify CouchDB version
* Strip the attachments param from the URL if <1.6 and display a warn message
* Add a note to the README

**Comment by dalgibbard** [comment]
I didn't find an easy way to determine the couchdb API version, as it often varied between old/new/git versions etc.
I've updated the documentation at least, and versions prior to 1.6 are pretty old now, so maybe we should just close this?

**Comment by csgui** [comment]
Maybe `curl ${host}:${port}` is an option to retrieve the CouchDB version? Or am I missing something?

**Comment by dalgibbard** [comment]
It's been a while, but iirc there were differences in the versioning format between older versions (before about 1.4ish?), git versions, current versions (say 1.6+) and future (2.0) versions.
But don't hold me to that :)
It's probably doable, but being that we've not had many requests/complaints it doesn't seem much worthwhile investing the time on.

**Comment by csgui** [comment]
Sure. Got you.

An information in the documentation about this usage restriction is enough! Feel free to close the issue. 

Cheers.

**Comment by dalgibbard** [comment]
Have done :) thanks!
