### ISSUE TITLE
"Document update conflict." does not result in Error of the script

### ISSUE THREAD

**Issue by yiu31802** [danielebailo/couchdb-dump#50]
There is an issue with error handling logic at
https://github.com/danielebailo/couchdb-dump/blob/master/couchdb-backup.sh#L510
where stderr always returns 0 for such kind of API error.

**Comment by yiu31802** [comment]
How to reproduce the issue:

Repeat the restore twice
`
./couchdb-backup.sh -r -H 127.0.0.1 -d mydb -f dumpedDB.json -u admin -p password
./couchdb-backup.sh -r -H 127.0.0.1 -d mydb -f dumpedDB.json -u admin -p password
`
Currently, both ends with successful imports whereas my fix commit turns it into Error.

**Comment by dalgibbard** [comment]
For my use case at least; this isn't an error scenario that I would want to stop at; if the document already exists, then there's no problem; just no need to rewrite it?

**Comment by yiu31802** [comment]
Well, for my use case, I update the backup file regularly with the same file name. Restoring the data using the file will induce the document conflict error and no update is performed at all.

... I would want to tell users what actually happens in the above scenario; I rather want to know that import was not performed at all instead of "Successful import". That is why I suggest the script should end up with error for this scenario.
