### ISSUE TITLE
Script doesn't continue

### ISSUE THREAD

**Issue by wasa4587** [danielebailo/couchdb-dump#52]
ERROR: Unable to post data to "http://localhost:5984/communities-api-dev/_bulk_docs" (http status code = 100)
i think it's because my file is huge  80M Aug 17 01:12 backup.js

**Comment by dalgibbard** [comment]
80M isn't that large at all; I've imported 2GB+ databases without encountering this issue myself. Do you have any proxies in front of it? Which CouchDB version are you using?
Is this still an issue on the latest code?

**Comment by dalgibbard** [comment]
Closed due to age and inactivity.
