### ISSUE TITLE
Problems with usernames and passwords (authorization failed)

### ISSUE THREAD

**Issue by ahodgkinson** [danielebailo/couchdb-dump#61]
How carefully has this script been tested with usernames and passwords? I ask because I am attempting to make a backup of a server that requires a username and password, and I keep getting authentication errors. I worry that this code never worked.

Upon investigation, I found that the following code caused problems (approx. line 273):

    if [ ! "x$username" = "x" ]&&[ ! "x$password" = "x" ]; then
        curlopt="${curlopt} -U '${username}:${password}'"
    fi

Which I patched to (and which also worked, though it's not a robust solution. See the note below):

    if [ ! "x$username" = "x" ]&&[ ! "x$password" = "x" ]; then
        curlopt="${curlopt} --user ${username}:${password}"
    fi

Changes:
  1. Changed `-U` to `--user`. E.g. Changed from `--proxy-user` to `--user` 
  1. The username & password single quotes are removed. With the single quotes, I think they are sent as part of the username/password.

Can you test that this change works and verify it works for you with servers that require a user name and password?

Note: This is not a complete fix. When you have usernames & password with special characters the `curl` command line will fail. The better solution is to refactor the `curl` command line and put the username/password quoting there, as is done with the `curl` URL. I can implement this once we know that the fix basically works.

**Comment by dalgibbard** [comment]
Which platform are you using?

**Comment by ahodgkinson** [comment]
This is a VM running Ubuntu Trusty (e.g. v 14.x), with CouchBase 1.5.0.
The couchdb-dump.sh and the CouchDB server are running on the same machine

**Comment by wirelessdreamer** [comment]
I get this same error, and the above solution does not resolve it. running on windows under cygwin

**Comment by tonklon** [comment]
I have the same problem and the same fix works for me on macOS 10.12.2. But this is not everything. To enable the restore function with username you must add `$curlopt` to every curl invocation. It's currently only present for the backup.
