### ISSUE TITLE
Is it possible to only append the delta of a file

### ISSUE THREAD

**Issue by Voolkanus** [danielebailo/couchdb-dump#64]
Hi,
I'm wondering if it's possible to only append the delta to a file and not to create a new file each time? I mean the option is currently not available, however did you guys considered to add it in the future? 
Thanks in advance!

**Comment by dalgibbard** [comment]
Can you provide an example of what you mean? Partial backups or something? Or bulk importing changes of document updates?

**Comment by Voolkanus** [comment]
What I meant is to take the same file and update only the changed/add only the new keys to the file and not to create each time a new file with the whole data. I'm thinking about creating continuos files and using the dump as a backup possibility.
Thanks!

**Comment by dalgibbard** [comment]
I see, so re-running a backup only pulls data since the last backup.
It's acheivable I believe, pretty sure the API supports it; but I suggest it's out of scope of the original focus of this tool.

Unless someone else wants to code it and raise a pull of course :)

**Comment by Voolkanus** [comment]
Well I was shooting in the dark here with the request, so thank you anyway for your consideration!
Good Luck.
