### ISSUE TITLE
Backup / restore all databases?

### ISSUE THREAD

**Issue by peteruithoven** [danielebailo/couchdb-dump#67]
Is there an easy / recommended way to backup / restore all databases under an account?

**Comment by dalgibbard** [comment]
Not really, you'd likely want to backup specific ones individually, else you'd be looking to restore them all at once also (which you might not want).

I'd suggest listing all DBs:
```
GET /_all_dbs
```
and then parsing that into a ```for i in``` type loop.

**Comment by peteruithoven** [comment]
> Not really, you'd likely want to backup specific ones individually, else you'd be looking to restore them all at once also (which you might not want).

I actually am looking for that, I'm looking for a way to make snapshots of the whole database. Most solutions don't support attachments.

**Comment by dalgibbard** [comment]
IIRC; this script does support backing up a database including attachments. But backing up _a_ database (with or without attachments) is a different request to backing up _all_ databases :) The attachments are not stored in a separate database.

Simply backup each database to it's own file, one-by-one, and then restore in the same manner.

**Comment by peteruithoven** [comment]
Thanks for the tips, I'll try your _all_dbs tip.
