### ISSUE TITLE
Stuck at 'Stage 1 - Document filtering'

### ISSUE THREAD

**Issue by peteruithoven** [danielebailo/couchdb-dump#68]
I'm using couchdb-dump version: 1.1.7

I have a database, which is successfully downloaded to a file (39MB), but it get's stuck at `Stage 1 - Document filtering`.
```
... INFO: Output file bob.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38.2M    0 38.2M    0     0  10.0M      0 --:--:--  0:00:03 --:--:-- 10.0M
... INFO: File may contain Windows carridge returns- converting...
... INFO: Completed successfully.
... INFO: Amending file to make it suitable for Import.
... INFO: Stage 1 - Document filtering
```

Since it's below 250MB, the parsing isn't multi-threaded. 

I'm assuming it's stuck at the sed line:
```
$sed_cmd ${sed_edit_in_place} 's/.*,"doc"://g'
```
Could someone what's the purpose of removing `.*,"doc":`? Is this the [Database Compaction](https://github.com/danielebailo/couchdb-dump#bonus-1-full-database-compaction) or [Purge Historic and Deleted Data](https://github.com/danielebailo/couchdb-dump#bonus-2-purge-historic-and-deleted-data) logic? 

Looking into the json file, it removed the following part on each line. 
```
{"id":"...","key":"...","value":{"rev":"..."},"doc":
```

I think a comment above that code is welcome. 

I'm assuming my issue is caused by binary attachments in all the docs.

I don't think I'm helped with #31, since I do want this to happen.

**Comment by peteruithoven** [comment]
Testing this just with that doc it seems like we can make that regular expression more performant by making the start more specific, using `s/{"id".*,"doc"://g`.
Does that make sense?

**Comment by dalgibbard** [comment]
Hey @peteruithoven - the initial raw export JSON from couchdb contains an encapsulating id/key/rev/doc section for each individual document within the database. To make the document importable back into couchdb, we need to strip this off; then the stage2 sed is to remove the leftover closing curly brace for this 'wrapping' section, and then sed sections 3 and 4 are to fix the header and footer of the JSON.
I think your proposed suggestion to make the sed statement more specific is valid and looks sane.

I don't have a means to test it right now- would you be able to confirm that the exported file is importable again using this change? And for the record, any detail of the speed improvement/time reduction as a result?

**Comment by peteruithoven** [comment]
Thanks for the clarifications. 

I've exported all my databases with the altered script, removed them and then reimported them. I haven't found any issues so far. 

In regards to speed, I've let old version work for > 10 minutes, on that 39MB file with no progress, I've not seen it finish at all. With my alteration, it takes maybe a few seconds.

**Comment by dalgibbard** [comment]
Merged and closed; thanks!

**Comment by peteruithoven** [comment]
Thanks for checking and merging

**Comment by epos-eu** [comment]
Thanks Darren
