### ISSUE TITLE
Is it possible to set the password with a environment variable?

### ISSUE THREAD

**Issue by pietervogelaar** [danielebailo/couchdb-dump#71]
The password with the -p parameter is visible with `ps aux`. Is it possible to specify the password with an environment variable?

**Comment by dalgibbard** [comment]
@pietervogelaar - have a look at #72 to see if that meets your requirements/works as expected :)

**Comment by dalgibbard** [comment]
To clarify; skip passing ```-p```/```-u``` on the command line, and instead set something like:
```
COUCHDB_USER=myuser COUCHDB_PASS=mysecretpass ./couchdb-dump.sh -args
# or export vars instead
```

**Comment by pietervogelaar** [comment]
Awesome, please merge! :-)

**Comment by dalgibbard** [comment]
All done, thanks for the suggestion :)
