### ISSUE TITLE
ERROR: Curl encountered an issue whilst dumping the database

### ISSUE THREAD

**Issue by barbalex** [danielebailo/couchdb-dump#74]
I am running this code in file `sichereBbAufDropbox.sh`:
```
# dumped artendb
# stellt dem Filenamen das Datum voran
# komprimiert das File
# kopiert das File auf die dropbox
# entfernt das File
FILENAME=$(date +"%Y-%m-%d_%H-%M-%S_artendb_dump.txt")
FILENAME_GZ=$FILENAME.tar.gz
/home/alex/backup/couchdb-backup.sh -b -H http://localhost:5984 -d artendb -f $FILENAME -u admin -p secret -P 5984
tar cvzf $FILENAME_GZ $FILENAME
/home/alex/backup/dropbox_uploader.sh upload $FILENAME_GZ $FILENAME_GZ
rm $FILENAME
rm $FILENAME_GZ
```

This is the output:
```
alex@ae-2018-01:~/backup$ bash sichereBbAufDropbox.sh
... INFO: Output file 2018-01-07_12-05-23_artendb_dump.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  197M    0  197M    0     0  4962k      0 --:--:--  0:00:40 --:--:--     0
curl: (18) transfer closed with outstanding read data remaining
... ERROR: Curl encountered an issue whilst dumping the database.
```

I am using:

- ubuntu 16.04.3
- couchdb 2.2.1
- curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
- couchdb-backup.sh downloaded today

This happens on a newly installed server. It used to work on the last server with the same db. I run similar backups on two other servers and they work fine.

**Comment by dalgibbard** [comment]
Sounds like either:
* CouchDB encountered an error (check logs)
* Network timeout or security issue (try running the backup directly on the DB host).

We're only using a standard curl call here which isn't anything fancy, so issue will be elsewhere.
