### ISSUE TITLE
can dump all revisions docs

### ISSUE THREAD

**Issue by victorc32** [danielebailo/couchdb-dump#77]
hello, 

Couchdb-dump is perfect and work perfectly , thanks a lot. 
But I have a little question , i want to dump all docs with all revisions ( for conserve history of docs) , on couchdb 2 cluster. It is possible  with update_seq option ?

Thanks .

Victor.

**Comment by dalgibbard** [comment]
For this use case, by far the simplest option is to just copy the .db file :)
Doing it via API involves getting all documents, and then for every document iterate through every revision iirc. And then, importing again won't create exactly the same DB really.

**Comment by victorc32** [comment]
thanks for your answer.
ok , it was first my idea, list all docs and for each list all revisions with  ?revs_info=true opition and after list  _revs_info" params for have all available rev, and make requests for import it.
Not exists other method ?
In couchdb 1.6, (not in cluster sure ;-) ) ; dumps and restaure couchdb db  with a tgz, was more simple.

**Comment by dalgibbard** [comment]
I'm not aware of any simpler method via the API - maybe reach out to the CouchDB devs on IRC and see if they have any thoughts on it?

**Comment by victorc32** [comment]
Thanks a lot Darren.

I will search with couchdb devs IRC .

Victor.
