### ISSUE TITLE
Invalid UTF-8 JSON error while restoring large file

### ISSUE THREAD

**Issue by cecchisandrone** [danielebailo/couchdb-dump#87]
I did a database export that has 44 MB / 33k lines. When restoring it, it is split into several `split*` files. When I try to restore the dump, I receive the following error:
```
[root@kazoo1 ~]# ./couchdb-dump.sh -a 1 -c -r -H localhost -d account%2F9b%2F7d%2Fa8712e54b4d596b51a1e74f58208 -f 9b7da8712e54b4d596b51a1e74f58208/account.json -P 15984
... INFO: Checking for database
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1613    0  1613    0     0   128k      0 --:--:-- --:--:-- --:--:--  131k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    12  100    12    0     0     74      0 --:--:-- --:--:-- --:--:--    74
... INFO: Checking for Design documents
... INFO: No Design Documents found for import.
... INFO: Block import set to 5000 lines.
... INFO: Generating files to import
... INFO: Header already applied to 9b7da8712e54b4d596b51a1e74f58208/account.json.splitaaa
... INFO: Adding footer to 9b7da8712e54b4d596b51a1e74f58208/account.json.splitaaa
... INFO: Inserting 9b7da8712e54b4d596b51a1e74f58208/account.json.splitaaa
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  533k  100    54  100  532k   1587  15.2M --:--:-- --:--:-- --:--:-- 15.7M
... ERROR: CouchDB Reported: {"error":"bad_request","reason":"invalid UTF-8 JSON"}
```
I checked `split*` and they are not valid JSON files, is that normal? What can I do for troubleshooting this? 
CouchDB version: 2.1.2
Thanks!

**Comment by dalgibbard** [comment]
I'd recommend loading the JSON in a JSON-friendly IDE, or sticking it through an online JSON validator to find out where the issue is.
My initial thinking is that you seem to have strange HTML character database names... What other strange stuff might be in that dump that needs escaping 😅

**Comment by cecchisandrone** [comment]
Well, the dump seems to be correct, I can open and validate it in VSCode. If I increase lines to 40000 it is imported correctly, so the problem is definitely a problem with the split. 
DB name is also correct (it has some escaped chars).
Do you know how the split files are created normally? Should they be valid JSON files or not?

**Comment by dalgibbard** [comment]
Yes, split files should be valid JSON, as they're loaded back into the DB during the restore process file-by-file (rather than being stitched back and inserted as a huge amount for example).

**Comment by cecchisandrone** [comment]
I found the reason for the issue. Basically, I was post-processing dump with `jq` and it was pretty-printing the file, causing `couchdb-dump` to get lost when splitting it in chunks. Thank you for your help in any case 😉

**Comment by dalgibbard** [comment]
All good then 😁
